# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsmConnect < Formula
  desc "Connect to EC2 instances via AWS SSM with automatic SSO authentication"
  homepage "https://github.com/shushpan/aws-ssm-connect"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shushpan/aws-ssm-connect/releases/download/v0.1.3/aws-ssm-connect_Darwin_x86_64.tar.gz"
      sha256 "f8b7fa2c6ad25721fe3efb41b692183acb1bb95fe474dfc313960bd09ed8ef1d"

      def install
        bin.install "aws-ssm-connect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shushpan/aws-ssm-connect/releases/download/v0.1.3/aws-ssm-connect_Darwin_arm64.tar.gz"
      sha256 "061fbaa19b7be1d27b92f101c5a8145bf73e9ec4b41a2f5b84c285a84d2bee41"

      def install
        bin.install "aws-ssm-connect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shushpan/aws-ssm-connect/releases/download/v0.1.3/aws-ssm-connect_Linux_x86_64.tar.gz"
        sha256 "110f14b3d9ab05a72bc3d6d789b277128fc8388a3fec45de8c8fc3ce1f7e359a"

        def install
          bin.install "aws-ssm-connect"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shushpan/aws-ssm-connect/releases/download/v0.1.3/aws-ssm-connect_Linux_arm64.tar.gz"
        sha256 "1736b85357b13f4287ef09d107845914ddc5d4201819ed7cd1114cf9374e09f5"

        def install
          bin.install "aws-ssm-connect"
        end
      end
    end
  end

  test do
    system "#{bin}/aws-ssm-connect --help"
  end
end
