# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsmConnect < Formula
  desc "Connect to EC2 instances via AWS SSM with automatic SSO authentication"
  homepage "https://github.com/shushpan/aws-ssm-connect"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shushpan/aws-ssm-connect/releases/download/v0.1.4/aws-ssm-connect_Darwin_x86_64.tar.gz"
      sha256 "10a557f5a450dd3d0703f0540e1ccbf1769ffb754c0a91f1c84993fcd3dba619"

      def install
        bin.install "aws-ssm-connect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shushpan/aws-ssm-connect/releases/download/v0.1.4/aws-ssm-connect_Darwin_arm64.tar.gz"
      sha256 "d3a1ec9a3ff29b3c15390c7ed5c7ebc54809630ee35396a88098ccf2ef4d2a5f"

      def install
        bin.install "aws-ssm-connect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shushpan/aws-ssm-connect/releases/download/v0.1.4/aws-ssm-connect_Linux_x86_64.tar.gz"
        sha256 "4830adefff39c779e248fdc1e4ae7a46469c3595b45b3963405583e0582ec17f"

        def install
          bin.install "aws-ssm-connect"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shushpan/aws-ssm-connect/releases/download/v0.1.4/aws-ssm-connect_Linux_arm64.tar.gz"
        sha256 "e4a22bc80e91a60c6d9c71750e64ec87f324bbaafd27f4e3d0457a49a27e5de2"

        def install
          bin.install "aws-ssm-connect"
        end
      end
    end
  end

  test do
    system "#{bin}/aws-ssm-connect --help"
  end
end
